# config/_default/config.toml

baseURL = "https://bortox.it/"
#enableGitInfo = true
theme = ["github.com/jpanther/congo/v2", "hugo-shortcode-gallery"]
defaultContentLanguage = "it"

[languages]
  [languages.it]
    languageCode = "it"
  [languages.en]
    languageCode = "en"

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 90
  resampleFilter = 'MitchellNetravali'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
home = ["HTML", "RSS", "JSON"]
timeout = 600000

[imaging.exif]
    includeFields = ".*"
