# config/_default/config.toml

baseURL = "https://bortox.it/"
#enableGitInfo = true
theme = ["github.com/jpanther/congo/v2", "hugo-shortcode-gallery"]
defaultContentLanguage = "it"
timeout = 600000


[permalinks]
  naver490fce001dfd0e85dbee2ca56d024e97 = "/naver490fce001dfd0e85dbee2ca56d024e97.html"

[languages]
  [languages.it]
    languageCode = "it"
  [languages.en]
    languageCode = "en"

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 90
  resampleFilter = 'NearestNeighbor'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
home = ["HTML", "RSS", "JSON"]

[imaging.exif]
    includeFields = ".*"
