# config/_default/config.toml

baseURL = "https://bortox.it/"
cacheVersion = "1.09"
#enableGitInfo = true

defaultContentLanguage = "it"

[languages]
  [languages.it]
    languageCode = "it"
  [languages.en]
    languageCode = "en"


[taxonomies]
  category = 'categories'
  tag = 'tags'

[outputs]
home = ["HTML", "RSS", "JSON"]