# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = ":house:"
  pageRef = "/"
  weight = 1

[[main]]
  name = "Blog :man_technologist:"
  pageRef = "article"
  weight = 10

[[main]]
  name = "Foto :camera:"
  url = "https://bortox.eu/"
  weight = 11

[[main]]
  name = "Scuola :memo:"
  pageRef = "compiti"
  weight = 12

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = ":house:"
  pageRef = "/"
  weight = 10

[[footer]]
  name = "Status :bar_chart:"
  url = "https://uptime.bortox.it"
  weight = 50

[[footer]]
  name = "Informativa sulla privacy :shield:"
  pageRef = "privacy"
  weight = 60

[[footer]]
  name = "Supporto :chart:"
  url = "https://bortox.it/contribuisci-cs/"
  weight = 45